# Generated by Django 4.2.16 on 2026-03-03 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_passwordresetotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLifestyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sleep_schedule', models.CharField(choices=[('early_bird', 'Early Bird'), ('night_owl', 'Night Owl'), ('balanced', 'Balanced')], max_length=20)),
                ('cleanliness', models.CharField(choices=[('minimal', 'Minimal'), ('organized', 'Organized'), ('relaxed', 'Relaxed')], max_length=20)),
                ('social_interaction', models.CharField(choices=[('introvert', 'Introvert'), ('extrovert', 'Extrovert'), ('moderate', 'Moderate')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
