# Generated by Django 4.2.16 on 2026-03-04 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_userlifestyle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlifestyle',
            name='cleanliness',
            field=models.CharField(choices=[('minimal', 'Minimalist'), ('organized', 'Organized'), ('relaxed', 'Relaxed')], max_length=20),
        ),
    ]
