# Generated by Django 4.2.16 on 2026-03-04 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_matchresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlifestyle',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='userlifestyle',
            name='cleanliness',
            field=models.CharField(choices=[('Minimalist', 'Minimalist'), ('Organized', 'Organized'), ('Relaxed', 'Relaxed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userlifestyle',
            name='sleep_schedule',
            field=models.CharField(choices=[('Early Bird', 'Early Bird'), ('Night Owl', 'Night Owl'), ('Balanced', 'Balanced')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userlifestyle',
            name='social_interaction',
            field=models.CharField(choices=[('Introvert', 'Introvert'), ('Extrovert', 'Extrovert'), ('Moderate', 'Moderate')], max_length=20),
        ),
    ]
