# Generated by Django 4.2.16 on 2026-03-05 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_userlifestyle_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchresult',
            name='matched_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matched_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='matchresult',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to=settings.AUTH_USER_MODEL),
        ),
    ]
