# Generated by Django 4.2.16 on 2026-03-09 03:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_favoritematch'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=255)),
                ('harmony_score', models.IntegerField(default=0)),
                ('target_location', models.CharField(blank=True, max_length=255, null=True)),
                ('compatibility_report', models.TextField(blank=True, null=True)),
                ('is_muted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_group_chats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GroupChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=100)),
                ('is_current_user', models.BooleanField(default=False)),
                ('message_type', models.CharField(choices=[('TEXT', 'Text'), ('ROOM_SHARE', 'Room Share')], default='TEXT', max_length=20)),
                ('content', models.TextField(blank=True, null=True)),
                ('room_title', models.CharField(blank=True, max_length=255, null=True)),
                ('room_price', models.CharField(blank=True, max_length=100, null=True)),
                ('room_beds', models.CharField(blank=True, max_length=50, null=True)),
                ('room_baths', models.CharField(blank=True, max_length=50, null=True)),
                ('schedule_tour_label', models.CharField(default='Schedule Tour', max_length=50)),
                ('book_room_label', models.CharField(default='Book Room', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.groupchat')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GroupChatMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='group_chat_members/')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='api.groupchat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('chat', 'user')},
            },
        ),
    ]
