# Generated by Django 4.2.16 on 2026-03-09 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_groupchat_groupchatmessage_groupchatmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupchatmessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='group_chat_images/'),
        ),
        migrations.AddField(
            model_name='groupchatmessage',
            name='image_source',
            field=models.CharField(blank=True, choices=[('gallery', 'Gallery'), ('camera', 'Camera')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='groupchatmessage',
            name='message_type',
            field=models.CharField(choices=[('TEXT', 'Text'), ('ROOM_SHARE', 'Room Share'), ('IMAGE', 'Image')], default='TEXT', max_length=20),
        ),
    ]
