# Generated by Django 4.2.16 on 2026-03-09 05:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_groupchatmessage_image_groupchatmessage_image_source_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomTourSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_title', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('selected_date', models.DateField()),
                ('selected_time', models.CharField(max_length=50)),
                ('meeting_point', models.CharField(default='Main Entrance of the building', max_length=255)),
                ('pro_tip', models.TextField(default='Bring your ID and any questions you have for the landlord.')),
                ('status', models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], default='CONFIRMED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_schedules', to='api.groupchat')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RoomBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_title', models.CharField(max_length=255)),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('security_deposit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('service_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_due_now', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method_last4', models.CharField(max_length=4)),
                ('payment_status', models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('PENDING', 'Pending'), ('FAILED', 'Failed')], default='CONFIRMED', max_length=20)),
                ('next_steps', models.TextField(default='Check your email for the digital lease.\nSchedule your move-in date in the chat.\nConnect with your new roommates!')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_bookings', to='api.groupchat')),
            ],
        ),
    ]
