# Generated by Django 4.2.16 on 2026-03-15 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_customuser_address_customuser_age_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listedroomphoto',
            old_name='uploaded_at',
            new_name='created_at',
        ),
        migrations.AlterUniqueTogether(
            name='groupchatmember',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='age',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='listedroom',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='roombooking',
            name='next_steps',
        ),
        migrations.AddField(
            model_name='listedroom',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='listedroom',
            name='bathroom_type',
            field=models.CharField(choices=[('PRIVATE_BATH', 'Private Bath'), ('SHARED_BATH', 'Shared Bath')], default='PRIVATE_BATH', max_length=20),
        ),
        migrations.AddField(
            model_name='listedroom',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='listedroom',
            name='entry_type',
            field=models.CharField(choices=[('KEYLESS', 'Keyless'), ('KEY_ENTRY', 'Key Entry'), ('SECURITY_DESK', 'Security Desk')], default='KEYLESS', max_length=20),
        ),
        migrations.AddField(
            model_name='listedroom',
            name='roommate_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='listedroom',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('SOLD_OUT', 'Sold Out')], default='AVAILABLE', max_length=20),
        ),
        migrations.AlterField(
            model_name='appnotification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='directchat',
            name='user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direct_chat_user1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='directchat',
            name='user2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direct_chat_user2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='directchatmessage',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direct_messages', to='api.directchat'),
        ),
        migrations.AlterField(
            model_name='favoritematch',
            name='matched_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='favoritematch',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_matches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='groupchat',
            name='harmony_score',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='groupchatmember',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='groupchatmember',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='group_members/'),
        ),
        migrations.AlterField(
            model_name='groupchatmessage',
            name='book_room_label',
            field=models.CharField(default='Book Room', max_length=100),
        ),
        migrations.AlterField(
            model_name='groupchatmessage',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='api.groupchat'),
        ),
        migrations.AlterField(
            model_name='groupchatmessage',
            name='image_source',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='groupchatmessage',
            name='message_type',
            field=models.CharField(choices=[('TEXT', 'Text'), ('IMAGE', 'Image'), ('ROOM_SHARE', 'Room Share')], default='TEXT', max_length=20),
        ),
        migrations.AlterField(
            model_name='groupchatmessage',
            name='schedule_tour_label',
            field=models.CharField(default='Schedule Tour', max_length=100),
        ),
        migrations.AlterField(
            model_name='roombooking',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.groupchat'),
        ),
        migrations.AlterField(
            model_name='roombooking',
            name='payment_method_last4',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='roombooking',
            name='payment_status',
            field=models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('PENDING', 'Pending')], default='CONFIRMED', max_length=20),
        ),
        migrations.AlterField(
            model_name='roomtourschedule',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.groupchat'),
        ),
        migrations.AlterField(
            model_name='roomtourschedule',
            name='meeting_point',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='roomtourschedule',
            name='pro_tip',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='roomtourschedule',
            name='status',
            field=models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('PENDING', 'Pending')], default='CONFIRMED', max_length=20),
        ),
        migrations.AlterField(
            model_name='useraccountsettings',
            name='language',
            field=models.CharField(default='English (US)', max_length=50),
        ),
        migrations.AlterField(
            model_name='useraccountsettings',
            name='privacy_settings',
            field=models.CharField(default='Default', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='target_area',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
