# Generated by Django 4.2.16 on 2026-03-15 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_rename_uploaded_at_listedroomphoto_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomShareRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro_message', models.TextField(blank=True, null=True)),
                ('preferred_move_in_date', models.DateField(blank=True, null=True)),
                ('duration_of_stay', models.CharField(blank=True, choices=[('3 Months', '3 Months'), ('6 Months', '6 Months'), ('9 Months', '9 Months'), ('12 Months', '12 Months'), ('18 Months', '18 Months'), ('24+ Months', '24+ Months')], max_length=20, null=True)),
                ('employment_status', models.CharField(blank=True, choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Student', 'Student'), ('Freelance', 'Freelance'), ('Unemployed', 'Unemployed')], max_length=20, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_share_requests', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_requests', to='api.listedroom')),
                ('room_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_share_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('room', 'requester')},
            },
        ),
    ]
