# Generated by Django 4.2.16 on 2026-03-16 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_roomsharerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomsharerequest',
            name='ai_background_check_completed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='roomsharerequest',
            name='group_security_deposit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='roomsharerequest',
            name='identity_document',
            field=models.FileField(blank=True, null=True, upload_to='identity_docs/'),
        ),
        migrations.AddField(
            model_name='roomsharerequest',
            name='identity_upload_source',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='roomsharerequest',
            name='identity_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roomsharerequest',
            name='total_move_in',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='roomsharerequest',
            name='your_share_monthly',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='roomsharerequest',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('SENT', 'Sent'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20),
        ),
    ]
