# Generated by Django 4.2.16 on 2026-03-19 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_userprofile_address_userprofile_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='rooms/')),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='about_me',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='age',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='bookings',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='budget_range',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='move_in_date',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='occupation',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_photo',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='room_status',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='saved_rooms',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='target_area',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='trust_score',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
