# Generated by Django 4.2.16 on 2026-03-21 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_remove_userprofile_profile_pic_userprofile_about_me_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchresult',
            name='ai_explanation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='matchresult',
            name='compatibility_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userbudgetlocation',
            name='monthly_budget',
            field=models.DecimalField(decimal_places=2, default=10000.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='userbudgetlocation',
            name='preferred_city',
            field=models.CharField(default='Chennai', max_length=255),
        ),
        migrations.AlterField(
            model_name='userlifestyle',
            name='cleanliness',
            field=models.CharField(choices=[('Minimalist', 'Minimalist'), ('Organized', 'Organized'), ('Relaxed', 'Relaxed')], default='Organized', max_length=20),
        ),
        migrations.AlterField(
            model_name='userlifestyle',
            name='sleep_schedule',
            field=models.CharField(choices=[('Early Bird', 'Early Bird'), ('Night Owl', 'Night Owl'), ('Balanced', 'Balanced')], default='Balanced', max_length=20),
        ),
        migrations.AlterField(
            model_name='userlifestyle',
            name='social_interaction',
            field=models.CharField(choices=[('Introvert', 'Introvert'), ('Extrovert', 'Extrovert'), ('Moderate', 'Moderate')], default='Moderate', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
