from django.urls import path
from .views import (
    SendOTPView,
    VerifyOTPView,
    RegisterView,
    LoginView,
    ForgotPasswordView,
    ResetPasswordView,
    UserLifestyleView,
    UserBudgetLocationView,
    UserProfileCreateUpdateView,
    UserProfileView,
    MatchListView,
    MatchDetailView,
    FavoriteListView,
    SaveFavoriteMatchView,
    ViewGroupDetailView,
    StartGroupChatView,
    GroupChatDetailView,
    GroupChatSendMessageView,
    GroupChatShareRoomDetailsView,
    GroupChatToggleMuteView,
    GroupChatUploadImageView,
    GroupChatEmojiListView,
    ScheduleRoomTourView,
    RoomTourDetailView,
    ConfirmRoomBookingView,
    RoomBookingDetailView,
    DirectChatCreateOrGetView,
    DirectChatDetailView,
    DirectChatSendMessageView,
    MessagesInboxView,
    ProfileDashboardView,
    ProfileUpdateView,
    ProfilePhotoUploadView,
    AccountSettingsView,
    ChangeEmailView,
    ChangePasswordView,
    DeleteAccountView,
    NotificationsListView,
    MarkNotificationReadView,
    ListedRoomCreateUpdateView,
    ListedRoomDetailView,
    LogoutView,
    DiscoverRoommatesView,
    RoommateProfileDetailView,
    AICompatibilityView,
)

urlpatterns = [
    path("send-otp/", SendOTPView.as_view(), name="send-otp"),
    path("verify-otp/", VerifyOTPView.as_view(), name="verify-otp"),
    path("register/", RegisterView.as_view(), name="register"),
    path("login/", LoginView.as_view(), name="login"),
    path("forgot-password/", ForgotPasswordView.as_view(), name="forgot-password"),
    path("reset-password/", ResetPasswordView.as_view(), name="reset-password"),

    path("lifestyle/", UserLifestyleView.as_view(), name="lifestyle"),
    path("budget-location/", UserBudgetLocationView.as_view(), name="budget-location"),

    path("user-profile/", UserProfileCreateUpdateView.as_view(), name="user-profile"),
    path("profile/<str:email>/", UserProfileView.as_view(), name="profile"),
    path("profile-dashboard/<str:email>/", ProfileDashboardView.as_view(), name="profile-dashboard"),
    path("profile-update/", ProfileUpdateView.as_view(), name="profile-update"),
    path("profile-photo-upload/", ProfilePhotoUploadView.as_view(), name="profile-photo-upload"),

    path("matches/<str:email>/", MatchListView.as_view(), name="matches"),
    path("match-detail/<int:match_id>/", MatchDetailView.as_view(), name="match-detail"),
    path("save-favorite/", SaveFavoriteMatchView.as_view(), name="save-favorite"),
    path("favorites/<str:email>/", FavoriteListView.as_view(), name="favorites"),

    path("discover-roommates/<str:email>/", DiscoverRoommatesView.as_view(), name="discover-roommates"),
    path("roommate-profile/<str:current_email>/<str:target_email>/", RoommateProfileDetailView.as_view(), name="roommate-profile-detail"),
    path("ai-compatibility/<str:current_email>/<str:target_email>/", AICompatibilityView.as_view(), name="ai-compatibility"),

    path("view-group/<str:email>/", ViewGroupDetailView.as_view(), name="view-group"),
    path("start-group-chat/", StartGroupChatView.as_view(), name="start-group-chat"),
    path("group-chat/<int:chat_id>/", GroupChatDetailView.as_view(), name="group-chat-detail"),
    path("group-chat/send-message/", GroupChatSendMessageView.as_view(), name="group-chat-send-message"),
    path("group-chat/share-room-details/", GroupChatShareRoomDetailsView.as_view(), name="group-chat-share-room-details"),
    path("group-chat/toggle-mute/", GroupChatToggleMuteView.as_view(), name="group-chat-toggle-mute"),
    path("group-chat/upload-image/", GroupChatUploadImageView.as_view(), name="group-chat-upload-image"),
    path("group-chat/emojis/", GroupChatEmojiListView.as_view(), name="group-chat-emojis"),

    path("schedule-room-tour/", ScheduleRoomTourView.as_view(), name="schedule-room-tour"),
    path("room-tour/<int:schedule_id>/", RoomTourDetailView.as_view(), name="room-tour-detail"),
    path("confirm-room-booking/", ConfirmRoomBookingView.as_view(), name="confirm-room-booking"),
    path("room-booking/<int:booking_id>/", RoomBookingDetailView.as_view(), name="room-booking-detail"),

    path("direct-chat/create/", DirectChatCreateOrGetView.as_view(), name="direct-chat-create"),
    path("direct-chat/<int:chat_id>/<str:email>/", DirectChatDetailView.as_view(), name="direct-chat-detail"),
    path("direct-chat/send-message/", DirectChatSendMessageView.as_view(), name="direct-chat-send-message"),
    path("messages/<str:email>/", MessagesInboxView.as_view(), name="messages-inbox"),

    path("account-settings/<str:email>/", AccountSettingsView.as_view(), name="account-settings-get"),
    path("account-settings/", AccountSettingsView.as_view(), name="account-settings-update"),
    path("change-email/", ChangeEmailView.as_view(), name="change-email"),
    path("change-password/", ChangePasswordView.as_view(), name="change-password"),
    path("delete-account/", DeleteAccountView.as_view(), name="delete-account"),

    path("notifications/<str:email>/", NotificationsListView.as_view(), name="notifications-list"),
    path("notifications/mark-read/", MarkNotificationReadView.as_view(), name="notifications-mark-read"),

    path("listed-room/", ListedRoomCreateUpdateView.as_view(), name="listed-room-create-update"),
    path("listed-room/<str:email>/", ListedRoomDetailView.as_view(), name="listed-room-detail"),

    path("logout/", LogoutView.as_view(), name="logout"),
]